FROM tensorflow/tensorflow:1.12.0-py3

ENV LANG=C.UTF-8
RUN mkdir /gpt-2
WORKDIR /gpt-2
ADD . /gpt-2
RUN pip3 install -r requirements.txt
ADD ./models/boys /gpt-2/models/boys
EXPOSE 80
ENTRYPOINT [ "./start-server.sh" ]